# Build using `bundle exec jekyll serve --drafts` (builds with posts in _drafts)
# Finished contents are in _site
# Settings recommended by GitHub.com setup guide for GitHub Pages with Jekyll
# From https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

title: MrGhorm
author: Matt Ghormley
email: matt@mrghorm.com
post_footer_comment: Any comments or questions?  Please feel free to reach out!
description: >- # this means to ignore newlines until "baseurl:"
  Thanks for visiting my site!  As you can see, this site
  is still under construction.  It will soon be home to technical
  write-ups, TryHackMe room walkthroughs, and instructional posts.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true

# GitHub Pages uses kramdown
markdown: kramdown

# Domain & URL
domain: mrghorm.com
url: https://mrghorm.com

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
